using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace ArchiveLoader
{
    public static class HTML
    {
        const string SiteURL = "https://github.com/MSDN-WhiteKnight/ruso-archive/";
        const string LicenseURL = "https://github.com/MSDN-WhiteKnight/ruso-archive/blob/master/LICENSE";

        public static void RenderPost(object post, TextWriter wr)
        {
            dynamic data = post as dynamic;
            dynamic owner = JSON.GetPropertyValue(data, "owner");
            string ownerstr;

            if (owner != null) ownerstr = String.Format("<a href=\"{0}\">{1}</a>", owner.link, owner.display_name);
            else ownerstr = "(unknown person)";

            wr.WriteLine("<html><head><meta charset=\"UTF-8\"/></head><body>");
            wr.WriteLine("<p><a href=\"{0}\">{1}</a> - by {2}</p>",data.link, data.link, ownerstr);
            wr.WriteLine("<blockquote>");
            wr.WriteLine(data.body);
            wr.WriteLine("</blockquote>");
            wr.WriteLine("<hr/>");
            wr.WriteLine("<p><i>Auto-generated by ruso-archive tools. Licensed under <a href=\""+LicenseURL+"\">CC-BY-4.0</a>.</i></p>");
            wr.WriteLine("</body></html>");
        }
    }
}
