using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace ArchiveLoader
{
    public static class HTML
    {
        public const string SiteURL = "https://github.com/MSDN-WhiteKnight/ruso-archive/";
        public const string LicenseURL = "https://github.com/MSDN-WhiteKnight/ruso-archive/blob/master/LICENSE";

        public static string GetOwnerString(object post)
        {
            dynamic owner = JSON.GetPropertyValue(post, "owner");
            dynamic owner_link = JSON.GetPropertyValue(owner, "link");
            string ownerstr;


            if (owner != null)
            {
                if (owner_link != null) ownerstr = String.Format("<a href=\"{0}\">{1}</a>", owner_link, owner.display_name);
                else ownerstr = owner.display_name;
            }
            else ownerstr = "(unknown person)";
            return ownerstr;
        }

        public static void RenderPost(object post, TextWriter wr)
        {
            dynamic data = post as dynamic;            
            string ownerstr = GetOwnerString(post);

            wr.WriteLine("<html><head><meta charset=\"UTF-8\"/><title>Post {0} | RuSO Archive</title></head><body>", data.post_id);
            wr.WriteLine("<p><i><a href=\"{0}\">RuSO Archive</a></i></p>", SiteURL);
            wr.WriteLine("<h2>Post {0}</h2>", data.post_id);
            wr.WriteLine("<p>Source: <a href=\"{0}\">{1}</a> - by {2}</p>",data.link, data.link, ownerstr);
            wr.WriteLine("<blockquote>");
            wr.WriteLine(data.body);
            wr.WriteLine("</blockquote>");
            wr.WriteLine("<hr/>");
            wr.WriteLine("<p><i>Retrieved from StackExchange API {0}</i></p>",DateTime.Now);
            wr.WriteLine("<p><i>Auto-generated by ruso-archive tools. ");
            wr.WriteLine("Content is licensed under <a href=\"{0}\">CC-BY-SA 4.0</a>.</i></p>", LicenseURL);
            wr.WriteLine("</body></html>");
        }

        public static void RenderHeader(int postid, TextWriter wr)
        {
            wr.WriteLine("<html><head><meta charset=\"UTF-8\"/><title>Post {0} | RuSO Archive</title></head><body>", postid);
            wr.WriteLine("<p><i><a href=\"{0}\">RuSO Archive</a></i></p>", SiteURL);            
        }

        public static void RenderBottom(TextWriter wr)
        {            
            wr.WriteLine("<hr/><p><i>Auto-generated by ruso-archive tools {0}. ", DateTime.Now);
            wr.WriteLine("Content is licensed under <a href=\"{0}\">CC-BY-SA 4.0</a>.</i></p>", LicenseURL);
            wr.WriteLine("</body></html>");
        }

        public static void RenderTOC(string site, string title, PostSet posts, TextWriter wr)
        {
            wr.WriteLine("<html><head><meta charset=\"UTF-8\"/><title>{0}: {1} | RuSO Archive</title></head><body>", site,title);
            wr.WriteLine("<p><i><a href=\"{0}\">RuSO Archive</a>: {1}</i></p>", SiteURL, title);
            wr.WriteLine("<h2>Questions from {0}</h2>", site);

            foreach (int key in posts.Questions.Keys)
            {
                wr.WriteLine("<p><a href=\"{0}.html\">{1}</a></p>", key, posts.Questions[key].DataDynamic.title);
            }

            wr.WriteLine("<h2>Answers from {0}</h2>", site);

            foreach (int key in posts.SingleAnswers.Keys)
            {
                wr.WriteLine("<p><a href=\"{0}.html\">Answer {1}</a></p>", key, key);
            }

            wr.WriteLine("<hr/>");
            wr.WriteLine("<p><i>Retrieved from StackExchange API.</i></p>");
            wr.WriteLine("<p><i>Auto-generated by ruso-archive tools {0}. ", DateTime.Now);
            wr.WriteLine("Content is licensed under <a href=\"{0}\">CC-BY-SA 4.0</a>.</i></p>", LicenseURL);
            wr.WriteLine("</body></html>");
        }
    }
}
