using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace ArchiveLoader
{
    public static class HTML
    {
        const string SiteURL = "https://github.com/MSDN-WhiteKnight/ruso-archive/";
        const string LicenseURL = "https://github.com/MSDN-WhiteKnight/ruso-archive/blob/master/LICENSE";

        public static void RenderPost(object post, TextWriter wr)
        {
            dynamic data = post as dynamic;
            dynamic owner = JSON.GetPropertyValue(data, "owner");
            string ownerstr;

            if (owner != null) ownerstr = String.Format("<a href=\"{0}\">{1}</a>", owner.link, owner.display_name);
            else ownerstr = "(unknown person)";

            wr.WriteLine("<html><head><meta charset=\"UTF-8\"/><title>Post {0} | RuSO Archive</title></head><body>", data.post_id);
            wr.WriteLine("<p><i><a href=\"{0}\">RuSO Archive</a></i></p>", SiteURL);
            wr.WriteLine("<h2>Post {0}</h2>", data.post_id);
            wr.WriteLine("<p>Source: <a href=\"{0}\">{1}</a> - by {2}</p>",data.link, data.link, ownerstr);
            wr.WriteLine("<blockquote>");
            wr.WriteLine(data.body);
            wr.WriteLine("</blockquote>");
            wr.WriteLine("<hr/>");
            wr.WriteLine("<p><i>Retrieved from StackExchange API {0}</i></p>",DateTime.Now);
            wr.WriteLine("<p><i>Auto-generated by ruso-archive tools. ");
            wr.WriteLine("Content is licensed under <a href=\"{0}\">CC-BY-4.0</a>.</i></p>", LicenseURL);
            wr.WriteLine("</body></html>");
        }
    }
}
