name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1    
    - name: Build with MSBuild
      run: |
        & "$env:windir\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" tools\src\RuSoTools.sln
    - name: Generate website
      run: |
        Set-Location -Path tools\src\ArchiveLoader\bin\Debug\; .\ArchiveLoader.exe generate
    - name: Build website with DocFX
      run: |
        choco install docfx; docfx .\docfx.json
    - name: Archive program binaries
      uses: actions/upload-artifact@v1
      with:
          name: Program
          path: tools\src\ArchiveLoader\bin\Debug\
    - name: Archive website build results
      uses: actions/upload-artifact@v1
      with:
          name: Website
          path: html\
