name: Update

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1    
    - name: Build with MSBuild
      run: |
        & "$env:windir\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" tools\src\RuSoTools.sln
    - name: Load data
      run: |
        Set-Location -Path tools\src\ArchiveLoader\bin\Debug\; .\ArchiveLoader.exe
    - name: Push changes
      run: |
        git checkout $env:GITHUB_REF_NAME; git add tools/data/*; git commit -m "CI update"; git push
